/**
 * This file was generated by openapi-typescript.
 * Do not edit this file directly.
 */

export interface paths {
  "/healthz": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
      };
    };
  };
  "/api/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
      };
    };
  };
  "/api/companies": {
    get: {
      parameters?: {
        query?: {
          skip?: number;
          limit?: number | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CompanyResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CompanyCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["CompanyResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/companies/{company_id}": {
    get: {
      parameters: {
        path: {
          company_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CompanyResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          company_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CompanyUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CompanyResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          company_id: number;
        };
      };
      responses: {
        204: {
          content: never;
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        409: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/contacts": {
    get: {
      parameters?: {
        query?: {
          skip?: number;
          limit?: number | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ContactResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ContactCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["ContactResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/contacts/{contact_id}": {
    get: {
      parameters: {
        path: {
          contact_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ContactResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          contact_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ContactUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ContactResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          contact_id: number;
        };
      };
      responses: {
        204: {
          content: never;
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/leads": {
    get: {
      parameters?: {
        query?: {
          skip?: number;
          limit?: number | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["LeadResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LeadCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["LeadResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/leads/{lead_id}": {
    get: {
      parameters: {
        path: {
          lead_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["LeadResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          lead_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LeadUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["LeadResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          lead_id: number;
        };
      };
      responses: {
        204: {
          content: never;
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/tasks": {
    get: {
      parameters?: {
        query?: {
          skip?: number;
          limit?: number | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TaskResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TaskCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["TaskResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/tasks/{task_id}": {
    get: {
      parameters: {
        path: {
          task_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TaskResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          task_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TaskUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TaskResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          task_id: number;
        };
      };
      responses: {
        204: {
          content: never;
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/interactions": {
    get: {
      parameters?: {
        query?: {
          skip?: number;
          limit?: number | null;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["InteractionResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["InteractionCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["InteractionResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/interactions/{interaction_id}": {
    get: {
      parameters: {
        path: {
          interaction_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["InteractionResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          interaction_id: number;
        };
      };
      responses: {
        405: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          interaction_id: number;
        };
      };
      responses: {
        405: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/dashboard": {
    get: {
      parameters?: {
        query?: {
          task_days?: number;
          interaction_limit?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["DashboardResponse"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    DashboardResponse: {
      pipeline_by_status: components["schemas"]["PipelineStatusSummary"][];
      upcoming_tasks: components["schemas"]["TaskResponse"][];
      overdue_tasks?: components["schemas"]["TaskResponse"][];
      recent_interactions: components["schemas"]["InteractionResponse"][];
    };
    PipelineStatusSummary: {
      status: string;
      count: number;
      total_value: number;
    };
    CompanyCreate: {
      name: string;
      email?: string | null;
      owner: string;
    };
    CompanyResponse: {
      id: number;
      name: string;
      email?: string | null;
      owner: string;
      created_at: string;
      updated_at: string;
    };
    CompanyUpdate: {
      name?: string | null;
      email?: string | null;
      owner?: string | null;
    };
    ContactCreate: {
      name: string;
      email: string;
      owner: string;
      company_id?: number | null;
    };
    ContactResponse: {
      id: number;
      name: string;
      email: string;
      owner: string;
      company_id?: number | null;
      created_at: string;
      updated_at: string;
    };
    ContactUpdate: {
      name?: string | null;
      email?: string | null;
      owner?: string | null;
      company_id?: number | null;
    };
    LeadCreate: {
      name: string;
      status: string;
      owner: string;
      company_id?: number | null;
    };
    LeadResponse: {
      id: number;
      name: string;
      status: string;
      owner: string;
      company_id?: number | null;
      created_at: string;
      updated_at: string;
    };
    LeadUpdate: {
      name?: string | null;
      status?: string | null;
      owner?: string | null;
      company_id?: number | null;
    };
    TaskCreate: {
      title: string;
      owner: string;
      due_date?: string | null;
      lead_id?: number | null;
      contact_id?: number | null;
      company_id?: number | null;
    };
    TaskResponse: {
      id: number;
      title: string;
      owner: string;
      due_date?: string | null;
      lead_id?: number | null;
      contact_id?: number | null;
      company_id?: number | null;
      overdue?: boolean;
      created_at: string;
      updated_at: string;
    };
    TaskUpdate: {
      title?: string | null;
      owner?: string | null;
      due_date?: string | null;
      lead_id?: number | null;
      contact_id?: number | null;
      company_id?: number | null;
    };
    InteractionCreate: {
      notes: string;
      timestamp: string;
      company_id?: number | null;
      contact_id?: number | null;
      lead_id?: number | null;
    };
    InteractionResponse: {
      id: number;
      notes: string;
      timestamp: string;
      company_id?: number | null;
      contact_id?: number | null;
      lead_id?: number | null;
      created_at: string;
    };
    FieldError: {
      field: string;
      message: string;
    };
    ErrorResponse: {
      error_code: string;
      message: string;
      fields?: components["schemas"]["FieldError"][] | null;
    };
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    ValidationError: {
      loc: (string | number)[];
      msg: string;
      type: string;
    };
  };
}
