"""Contract tests for backend OpenAPI schema verification.

Ensures that the runtime OpenAPI specification generated by the FastAPI application
matches the committed OpenAPI contract (`contracts/openapi.json`).
"""

import json
from pathlib import Path
from typing import Any, Dict

from api.main import app


def _get_contracts_dir() -> Path:
    """Find and return the path to the root `contracts` directory."""
    current = Path(__file__).resolve()
    for parent in current.parents:
        contracts_dir = parent / "contracts"
        if contracts_dir.exists() and contracts_dir.is_dir():
            return contracts_dir
    raise FileNotFoundError("Could not locate 'contracts' directory in repository root.")


def test_committed_openapi_spec_exists() -> None:
    """Assert that the committed contracts/openapi.json specification file exists."""
    contracts_dir = _get_contracts_dir()
    spec_path = contracts_dir / "openapi.json"
    assert spec_path.exists(), f"Committed OpenAPI spec not found at {spec_path}"
    assert spec_path.is_file(), f"Path {spec_path} is not a file"


def test_generated_openapi_matches_committed_spec() -> None:
    """Assert that generated FastAPI app.openapi() matches committed contracts/openapi.json."""
    contracts_dir = _get_contracts_dir()
    spec_path = contracts_dir / "openapi.json"
    assert spec_path.exists(), f"Committed spec file missing at {spec_path}"

    with open(spec_path, "r", encoding="utf-8") as f:
        committed_spec: Dict[str, Any] = json.load(f)

    generated_spec: Dict[str, Any] = app.openapi()

    assert generated_spec == committed_spec, (
        "Generated OpenAPI specification does not match committed contracts/openapi.json! "
        "If API routes or models were changed, regenerate and commit contracts/openapi.json."
    )


def test_openapi_schema_has_required_endpoints() -> None:
    """Assert that all expected API routes are documented in the OpenAPI schema."""
    generated_spec: Dict[str, Any] = app.openapi()
    paths = generated_spec.get("paths", {})

    expected_routes = [
        "/healthz",
        "/api/health",
        "/api/companies",
        "/api/companies/{company_id}",
        "/api/contacts",
        "/api/contacts/{contact_id}",
        "/api/leads",
        "/api/leads/{lead_id}",
        "/api/tasks",
        "/api/tasks/{task_id}",
        "/api/interactions",
        "/api/interactions/{interaction_id}",
        "/api/dashboard",
    ]

    for route in expected_routes:
        assert route in paths, f"Expected route {route} missing from OpenAPI schema paths"


def test_openapi_schema_metadata() -> None:
    """Assert basic metadata fields in generated OpenAPI schema."""
    generated_spec: Dict[str, Any] = app.openapi()
    info = generated_spec.get("info", {})

    assert info.get("title") == "CRM Platform API"
    assert info.get("version") == "1.0.0"
    assert "openapi" in generated_spec
    assert str(generated_spec["openapi"]).startswith("3.")


def test_openapi_schema_structure() -> None:
    """Assert essential top-level structures in the OpenAPI schema."""
    generated_spec: Dict[str, Any] = app.openapi()
    assert "openapi" in generated_spec
    assert "info" in generated_spec
    assert "paths" in generated_spec
    assert "components" in generated_spec
    assert "schemas" in generated_spec["components"]
